### PR TITLE
Add @sigmavirus24

### PR DESCRIPTION
**Pull request by jakirkham**
Adds @sigmavirus24 as a maintainer. Please let me know if this is ok, @sigmavirus24.

### CODE REVIEW

**Comment by dopplershift** [comment]
👍  Just waiting on confirmation from @sigmavirus24

**Comment by jakirkham** [comment]
FWIW that's the only reason this says "WIP". If he confirms, feel free to remove "WIP" and merge.

**Comment by sigmavirus24** [comment]
Woops. Sorry. Absolutely happy to help with this.

**Comment by jakirkham** [comment]
No worries. Wasn't trying to force a fast response.

**Pull request merged**
